<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>34882693977ae1f266e18c37</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-09-11 10:56:26</createtime><buildsignature>Local.Unknown.Unknown.1.108.349.1020-1.300.000.189.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>34882693977ae1f266e18c37</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while starting situation (AttributeError: 'object_Baby' object has no attribute 'is_being_destroyed')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 130, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 126, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 383, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 609, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1659, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 970, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1440, in finalize&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2427, in finalize&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\baby\baby.py", line 597, in on_finalize_load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\baby\baby.py", line 332, in set_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\baby\baby.py", line 500, in enable_baby_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\buff_component.py", line 244, in on_bassinet_ready_to_simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\buff.py", line 1490, in on_bassinet_ready_to_simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\buff.py", line 1758, in _start_auto_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 281, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 258, in start_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_manager.py", line 693, in create_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_manager.py", line 854, in create_situation_from_seed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 475, in start_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_complex.py", line 1147, in _change_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 40, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 274, in on_enter_passive_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 352, in _update_caregiver_status&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 255, in get_care_dependent_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_Baby' object has no attribute 'is_being_destroyed'rtim=0&#13;&#10;Client Session Time: 28.30&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,288,0,5801&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.16299 GPU: Intel(R) UHD Graphics igdumdim64.dll 30.0.101.1692, GUID: D7B78E66-C916-11CF-6F75-A43EA8C2D335&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>34882693977ae1f266e18c37</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-09-11 11:04:16</createtime><buildsignature>Local.Unknown.Unknown.1.108.349.1020-1.300.000.189.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>34882693977ae1f266e18c37</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while starting situation (AttributeError: 'object_Baby' object has no attribute 'is_being_destroyed')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 130, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 126, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 383, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 609, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1659, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 970, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1440, in finalize&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2427, in finalize&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\baby\baby.py", line 597, in on_finalize_load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\baby\baby.py", line 332, in set_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\baby\baby.py", line 500, in enable_baby_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\buff_component.py", line 244, in on_bassinet_ready_to_simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\buff.py", line 1490, in on_bassinet_ready_to_simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\buff.py", line 1758, in _start_auto_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 281, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 258, in start_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_manager.py", line 693, in create_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_manager.py", line 854, in create_situation_from_seed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 475, in start_situation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_complex.py", line 1147, in _change_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 40, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 274, in on_enter_passive_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 352, in _update_caregiver_status&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\complex\caregiver_situation.py", line 255, in get_care_dependent_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_Baby' object has no attribute 'is_being_destroyed'rtim=0&#13;&#10;Client Session Time: 28.30&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,288,0,5801&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.16299 GPU: Intel(R) UHD Graphics igdumdim64.dll 30.0.101.1692, GUID: D7B78E66-C916-11CF-6F75-A43EA8C2D335&#13; &#10;</desyncdata></report>
</root>